;;;                                ********
;;;
;;; Copyright 1992 by BBN Systems and Technologies, A division of Bolt,
;;; Beranek and Newman Inc.
;;; 
;;; Permission to use, copy, modify and distribute this software and its
;;; documentation is hereby granted without fee, provided that the above
;;; copyright notice and this permission appear in all copies and in
;;; supporting documentation, and that the name Bolt, Beranek and Newman
;;; Inc. not be used in advertising or publicity pertaining to distribution
;;; of the software without specific, written prior permission.  In
;;; addition, BBN makes no respresentation about the suitability of this
;;; software for any purposes.  It is provided "AS IS" without express or
;;; implied warranties including (but not limited to) all implied warranties
;;; of merchantability and fitness.  In no event shall BBN be liable for any
;;; special, indirect or consequential damages whatsoever resulting from
;;; loss of use, data or profits, whether in an action of contract,
;;; negligence or other tortuous action, arising out of or in connection
;;; with the use or performance of this software.
;;; 
;;;                                 ********
;;; 
;;;("Date:" (90 4 5) "Time:" (20 9 4))
("setup-packages" "cl-fluids"
                  "system-init"
                  "system-config"
                  "package-e"
                  "package-d"
                  "package-c"
                  "package-b"
                  "package-a"
                  "package-common"
                  "misc-exports"
                  "parallel"
                  "modules"
                  "cl-errset"
                  "error"
                  "printer-interface"
                  "reader-interface"
                  "stream-interface"
                  "filesys"
                  "arith-defs-k"
                  "arith-defs-j"
                  "arith-defs-i"
                  "clchap16-b"
                  "clchap16-a-2"
                  "clchap16-a-1"
                  "clchap16-comm"
                  "clchap19"
                  "clchap11"
                  "cl-string"
                  "cl-array-2"
                  "clchap20"
                  "normalize-type-expr"
                  "sequence-sort"
                  "sequence-search"
                  "sequence-modify"
                  "sequence-map"
                  "sequence-simple"
                  "subtypep"
                  "cl-coerce"
                  "cl-array"
                  "typep"
                  "typespec"
                  "clchap7f"
                  "clchap7e"
                  "clchap25"
                  "clchap15a"
                  "clchap7d-b"
                  "clchap7d-a"
                  "check-type"
                  "clchap7c-b-2"
                  "clchap7c-b-1"
                  "clchap7c-a"
                  "clchap7c-comm"
                  "clchap8a"
                  "clchap8-c"
                  "clchap8-b-2"
                  "clchap8-b-1"
                  "clchap8-a"
                  "clchap8-comm"
                  "clchap7a"
                  "clchap15"
                  "clchap13"
                  "equalp"
                  "lambda-constants"
                  "arith-constants"
                  "clchap5a"
                  "clchap10"
                  "clchap9"
                  "clchap7b"
                  "clchap7"
                  "predicates"
                  "defun"
                  "clchap5-b"
                  "clchap5-a"
                  "cl-util2"
                  "cl-util"
                  "localinit"
                  "cl-array-prims"
                  "arith"
                  "proclaim"
                  "initial-optimizers"
                  "np-inline"
                  "optimizer-interface"
                  "integration-stubs"
                  "cl-macros"
                  "exported-scheme-builtins"
                  "boot-np-inline"
                  "cl-compile-file"
                  "cl-pp"
                  "cl-format"
                  "cl-unparse"
                  "cl-readtable"
                  "cl-parse"
                  "make-cl-io"
                  "values"
                  "errset"
                  "syntax-extensions"
                  "cl-kernel"
                  "cl-fixobj"
                  "pkg-extensions"
                  "symbol"
                  "cl-error-boot"
                  "impurify-patch")