#| -*-Scheme-*-

<<<<<<< Xlib.scm
$Header: Xlib.scm,v 13.90 88/06/06 08:59:49 ajc Exp $
=======
$Header: Xlib.scm,v 13.90 88/06/06 08:59:49 ajc Exp $
>>>>>>> 13.80.2.1

Copyright (c) 1987 Massachusetts Institute of Technology

This material was developed by the Scheme project at the Massachusetts
Institute of Technology, Department of Electrical Engineering and
Computer Science.  Permission to copy this software, to redistribute
it, and to use it for any purpose is granted, subject to the following
restrictions and understandings.

1. Any copy made of this software must include this copyright notice
in full.

2. Users of this software agree to make their best efforts (a) to
return to the MIT Scheme project any improvements or extensions that
they make, so that these may be included in future releases; and (b)
to inform MIT of noteworthy uses of this software.

3. All materials developed as a consequence of the use of this
software shall duly acknowledge such use, in accordance with the usual
standards of acknowledging credit in academic research.

4. MIT has made no warrantee or representation that the operation of
this software will be error-free, and MIT is under no obligation to
provide any services, by way of maintenance, update, or otherwise.

5. In conjunction with products arising from the use of this material,
there shall be no use of the name of the Massachusetts Institute of
Technology nor of any adaptation thereof in any advertising,
promotional, or sales literature without prior written consent from
MIT in each case. |#

;;;; Xlib Interface Definitions

(declare (usual-integrations))

;;;; Primitives implemented in "Xrep.c".

(let-syntax ((define-primitive
	       (macro (name arity)
		 `(DEFINE ,name ,(make-primitive-procedure name arity)))))
  (define-primitive x-object=? 2)
  (define-primitive x-display->root 1)
  (define-primitive x-display->vnumber 1)
  (define-primitive x-display->dtype 1)
  (define-primitive x-display->dplanes 1)
  (define-primitive x-display->dcells 1)
  (define-primitive x-display->qlen 1)
  (define-primitive x-display->black 1)
  (define-primitive x-display->white 1)
  (define-primitive x-display->displayname 1)
  (define-primitive x-display->width 1)
  (define-primitive x-display->height 1)
  (define-primitive x-make-opaque-frame 7)
  (define-primitive x-opaque-frame->self 1)
  (define-primitive x-opaque-frame->x 1)
  (define-primitive x-opaque-frame->y 1)
  (define-primitive x-opaque-frame->width 1)
  (define-primitive x-opaque-frame->height 1)
  (define-primitive x-opaque-frame->border-width 1)
  (define-primitive x-opaque-frame->border 1)
  (define-primitive x-opaque-frame->background 1)
  (define-primitive x-make-transparent-frame 4)
  (define-primitive x-transparent-frame->self 1)
  (define-primitive x-transparent-frame->x 1)
  (define-primitive x-transparent-frame->y 1)
  (define-primitive x-transparent-frame->width 1)
  (define-primitive x-transparent-frame->height 1)
  (define-primitive x-make-batch-frame 9)
  (define-primitive x-batch-frame-type 1)
  (define-primitive x-batch-frame-parent 1)
  (define-primitive x-batch-frame-self 1)
  (define-primitive x-batch-frame->x 1)
  (define-primitive x-batch-frame->y 1)
  (define-primitive x-batch-frame->width 1)
  (define-primitive x-batch-frame->height 1)
  (define-primitive x-batch-frame->border-width 1)
  (define-primitive x-batch-frame->border 1)
  (define-primitive x-batch-frame->background 1)
  (define-primitive x-window-info->width 1)
  (define-primitive x-window-info->height 1)
  (define-primitive x-window-info->x 1)
  (define-primitive x-window-info->y 1)
  (define-primitive x-window-info->border-width 1)
  (define-primitive x-window-info->mapped 1)
  (define-primitive x-window-info->type 1)
  (define-primitive x-window-info->assoc-window 1)
  (define-primitive x-color->pixel 1)
  (define-primitive x-color->red 1)
  (define-primitive x-color->green 1)
  (define-primitive x-color->blue 1)
  (define-primitive x-font-info->id 1)
  (define-primitive x-font-info->height 1)
  (define-primitive x-font-info->width 1)
  (define-primitive x-font-info->baseline 1)
  (define-primitive x-font-info->fixedwidth 1)
  (define-primitive x-font-info->firstchar 1)
  (define-primitive x-font-info->lastchar 1)
  (define-primitive x-event-type 1)
  (define-primitive x-event-window 1)
  (define-primitive x-event-subwindow 1)
  (define-primitive x-key-event-time 1)
  (define-primitive x-key-event-detail 1)
  (define-primitive x-key-event-x 1)
  (define-primitive x-key-event-y 1)
  (define-primitive x-key-event-location 1)
  (define-primitive x-expose-event-width 1)
  (define-primitive x-expose-event-height 1)
  (define-primitive x-expose-event-x 1)
  (define-primitive x-expose-event-y 1)

;;;; Primitives implemented in "Xlib.c".

  (define-primitive x-open-display 1)
  (define-primitive x-set-display 1)
  (define-primitive x-close-display 1)
  (define-primitive x-display-type 0)
  (define-primitive x-display-planes 0)
  (define-primitive x-display-cells 0)
  (define-primitive x-protocol-version 0)
  (define-primitive x-queue-length 0)
  (define-primitive x-display-width 0)
  (define-primitive x-display-height 0)
  (define-primitive x-root-window 0)
  (define-primitive x-black-pixmap 0)
  (define-primitive x-white-pixmap 0)
  (define-primitive x-selected-display 0)
  (define-primitive x-create-window 8)
  (define-primitive x-create-transparency 5)
  (define-primitive x-destroy-window 1)
  (define-primitive x-destroy-subwindows 1)
  (define-primitive x-create 7)
  (define-primitive x-create-term 12)
  (define-primitive x-create-windows 2)
  (define-primitive x-create-transparencies 2)
  (define-primitive x-create-window-batch 1)
  (define-primitive x-map-window 1)
  (define-primitive x-map-subwindows 1)
  (define-primitive x-unmap-window 1)
  (define-primitive x-unmap-transparent 1)
  (define-primitive x-unmap-subwindows 1)
  (define-primitive x-move-window 3)
  (define-primitive x-change-window 3)
  (define-primitive x-configure-window 5)
  (define-primitive x-raise-window 1)
  (define-primitive x-lower-window 1)
  (define-primitive x-circle-window-up 1)
  (define-primitive x-circle-window-down 1)
  (define-primitive x-query-window 1)
  (define-primitive x-query-tree 1)
  (define-primitive x-change-background 2)
  (define-primitive x-change-border 2)
  (define-primitive x-tile-absolute 1)
  (define-primitive x-tile-relative 1)
  (define-primitive x-clip-draw-through 1)
  (define-primitive x-clip-clipped 1)
  (define-primitive x-store-name 2)
  (define-primitive x-fetch-name 1)
  (define-primitive x-set-resize-hint 5)
  (define-primitive x-get-resize-hint 1)
  (define-primitive x-set-icon-window 2)
  (define-primitive x-clear-icon-window 1)
  (define-primitive x-query-mouse 1)
  (define-primitive x-query-mouse-buttons 1)
  (define-primitive x-update-mouse 1)
  (define-primitive x-warp-mouse 3)
  (define-primitive x-cond-warp-mouse 8)
  (define-primitive x-interpret-locator 2)
  (define-primitive x-clear 1)
  (define-primitive x-pix-set 6)
  (define-primitive x-pix-fill 9)
  (define-primitive x-pixmap-put 10)
  (define-primitive x-query-tile-shape 2)
  (define-primitive x-tile-set 6)
  (define-primitive x-tile-fill 9)
  (define-primitive x-stipple-fill 9)
  (define-primitive x-move-area 7)
  (define-primitive x-copy-area 9)
  (define-primitive x-pixmap-bits-put-xy 9)
  (define-primitive x-pixmap-bits-put-z 9)
  (define-primitive x-bitmap-bits-put 11)
  (define-primitive x-pixmap-save 5)
  (define-primitive x-pixmap-get-xy 5)
  (define-primitive x-pixmap-get-z 5)
  (define-primitive x-store-pixmap-xy 3)
  (define-primitive x-store-pixmap-z 3)
  (define-primitive x-store-bitmap 3)
  (define-primitive x-make-pixmap 3)
  (define-primitive x-make-tile 1)
  (define-primitive x-free-pixmap 1)
  (define-primitive x-free-bitmap 1)
  (define-primitive x-char-bitmap 2)
  (define-primitive x-store-cursor 7)
  (define-primitive x-query-cursor-shape 2)
  (define-primitive x-free-cursor 1)
  (define-primitive x-create-cursor 9)
  (define-primitive x-define-cursor 2)
  (define-primitive x-undefine-cursor 1)
  (define-primitive x-get-hardware-color 1)
  (define-primitive x-parse-color 1)
  (define-primitive x-get-font 1)
  (define-primitive x-query-font 1)
  (define-primitive x-free-font 1)
  (define-primitive x-text 7)
  (define-primitive x-text-pad 12)
  (define-primitive x-text-mask 7)
  (define-primitive x-text-mask-pad 11)
  (define-primitive x-mouse-control 2)
  (define-primitive x-feep-control 1)
  (define-primitive x-feep 1)
  (define-primitive x-key-click-control 1)
  (define-primitive x-auto-repeat-on 0)
  (define-primitive x-auto-repeat-off 0)
  (define-primitive x-lock-up/down 0)
  (define-primitive x-lock-toggle 0)
  (define-primitive x-screen-saver 3)
  (define-primitive x-get-default 2)
  (define-primitive x-parse-geometry 1)
  (define-primitive x-geometry 7)
  (define-primitive x-read-bitmap-file 1)
  (define-primitive x-store-bytes 1)
  (define-primitive x-fetch-bytes 0)
  (define-primitive x-rotate-buffers 1)
  (define-primitive x-store-buffer 2)
  (define-primitive x-append-buffer 2)
  (define-primitive x-fetch-buffer 1)
  (define-primitive x-compress-events 0)
  (define-primitive x-expand-events 0)
  (define-primitive x-select-input 2)
  (define-primitive x-query-input 1)
  (define-primitive x-flush 0)
  (define-primitive x-sync 1)
  (define-primitive x-pending 0)
  (define-primitive x-next-event 0)
  (define-primitive x-put-back-event 1)
  (define-primitive x-peek-event 0)
  (define-primitive x-window-event 2)
  (define-primitive x-mask-event 1)
  (define-primitive x-check-window-event 2)
  (define-primitive x-check-mask-event 1)
  (define-primitive x-grab-mouse 3)
  (define-primitive x-ungrab-mouse 0)
  (define-primitive x-grab-button 4)
  (define-primitive x-ungrab-button 1)
  (define-primitive x-grab-server 0)
  (define-primitive x-ungrab-server 0)
  (define-primitive x-focus-keyboard 1)
  (define-primitive x-lookup-mapping 1)
  (define-primitive x-rebind-code 3)
  (define-primitive x-use-keymap 1))

((make-primitive-procedure 'X-INITIALIZE 0))

;;;; Various Constants

(define pixel-value/black 0)
(define pixel-value/white 1)

(define mapped-type/unmapped 0)
(define mapped-type/mapped 1)
(define mapped-type/invisible 2)

(define window-type/transparent 0)
(define window-type/opaque 1)
(define window-type/icon 2)

(define gx/clear 0)
(define gx/and 1)
(define gx/and-reverse 2)
(define gx/copy 3)
(define gx/and-inverted 4)
(define gx/noop 5)
(define gx/xor 6)
(define gx/or 7)
(define gx/nor 8)
(define gx/equiv 9)
(define gx/invert 10)
(define gx/or-reverse 11)
(define gx/copy-inverted 12)
(define gx/or-inverted 13)
(define gx/nand 14)
(define gx/set 15)

(define vertex/relative #x0001)
(define vertex/dont-draw #x0002)
(define vertex/curved #x0004)
(define vertex/start-closed #x0008)
(define vertex/end-closed #x0010)
(define vertex/draw-last-point #x0020)

(define event-type/key-pressed #x0001)
(define event-type/key-released #x0002)
(define event-type/button-pressed #x0004)
(define event-type/button-released #x0008)
(define event-type/enter-window #x0010)
(define event-type/leave-window #x0020)
(define event-type/mouse-moved #x0040)
(define event-type/expose-window #x0080)
(define event-type/expose-region #x0100)
(define event-type/expose-copy #x0200)
(define event-type/right-down-motion #x0400)
(define event-type/middle-down-motion #x0800)
(define event-type/left-down-motion #x1000)
(define event-type/unmap-window #x2000)
(define event-type/focus-change #x4000)

